# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-15 22:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='正文')),
                ('images', models.ImageField(upload_to='images')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('times', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField(verbose_name='评论')),
                ('times', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SelfBlog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SelfBlog.Types'),
        ),
    ]
